// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfkvehabumalciwwgluq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBma3ZlaGFidW1hbGNpd3dnbHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNzY1MTUsImV4cCI6MjA1ODk1MjUxNX0.B4_RHxR9D2k9kEDBgSm3X-A8St2UIJuy4QmCvaxLtY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);